[char_server]
name = "char-test-1"
address = "127.0.0.1"
port = 6901

[starting_characters.novice]
items = [
    { id = 1201, amount = 1, slot = 2 },
    { id = 2301, amount = 1, slot = 16 },
]

[starting_characters.doram]
items = [
    { id = 1681, amount = 1, slot = 2 },
    { id = 2301, amount = 1, slot = 16 },
]

[maps]
names_file = "../resources/maps.yaml"
