[package]
name = "api"
version = "0.1.0"
authors = ["Sam De Roeck <sadroeck@gmail.com>"]
edition = "2018"

[dependencies]
async-trait = "0.1"
async-codec = "0.4"
async-std = "1.8"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
stackvec = "0.2"
thiserror = "1.0"
tracing = "0.1"